
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeultnetrrcyxvvezyci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpldWx0bmV0cnJjeXh2dmV6eWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzA0MDIsImV4cCI6MjA1NzUwNjQwMn0.tUssPfGoFN-uDG25S6yKnS-GSNVtaytzFjhJcj7cuHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
